name: "Call Dependabot reviewer"

on: pull_request_target

permissions:
  pull-requests: write
  contents: write

jobs:
  call-dependabot-reviewer:
    uses: CheeziCrew/testConfig/.github/workflows/common-dependabot-reviewer.yml@main
